# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-06 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customerUser', '0002_auto_20180206_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_birth',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], default=b'M', max_length=1, verbose_name=b'Gender'),
        ),
    ]
