# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-06 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('customerUser', '0003_auto_20180206_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_birth',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=b'1390000000', max_length=128, verbose_name='Phone number'),
        ),
    ]
